# Generated by Django 2.2.14 on 2020-08-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
