# Generated by Django 2.2.14 on 2020-08-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_tag_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tags', to='newsletters.Newsletter')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters_tagged', to='newsletters.Tag')),
            ],
            options={
                'unique_together': {('newsletter', 'tag')},
            },
        ),
    ]
