# Generated by Django 2.2.14 on 2020-08-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20200824_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter_Tag',
            new_name='NewsLetterTag',
        ),
    ]
